### ISSUE TITLE
Add buttons "Add/Remove sensors" to forge-dataviz-iot-reference-app

### ISSUE THREAD

**Issue by wallabyway** [yiskang/forge-dataviz-2d#1]
https://github.com/yiskang/forge-dataviz-iot-reference-app

**Comment by yiskang** [comment]
Add backend support, but will need time to learn modern React and modify the frontend code.

https://github.com/yiskang/forge-dataviz-iot-reference-app/commits/json-db

**Comment by yiskang** [comment]
Hi @wallabyway, I have ported the sensor manager ext w/o using react.js to forge-dataviz-iot-reference-app. You can see the code here:

- Code changes: https://github.com/yiskang/forge-dataviz-iot-reference-app/commits/json-db
- Demo: https://youtu.be/z4c_0Kd8Nhg

If it's ok for you, I will create a PR to https://github.com/Autodesk-Forge/forge-dataviz-iot-reference-app
